### ISSUE TITLE
Auth and Pool Issues

### ISSUE THREAD

**Issue by joshcsullivan** [standardnotes/standalone#1]
Following the directions at https://docs.standardnotes.org/self-hosting/docker/ and running into a couple issues.

First the PoolCluster is giving errors, I'm assuming because I don't have a cluster:
```
db_1                        | 2021-05-14 15:19:45+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.6.51-1debian9 started.
db_1                        | 2021-05-14 15:19:45+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1                        | 2021-05-14 15:19:46+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.6.51-1debian9 started.
syncing-server-js-worker_1  | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.3:3306
syncing-server-js-worker_1  | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.3:3306
syncing-server-js-worker_1  | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.3:3306
syncing-server-js-worker_1  | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.3:3306
syncing-server-js-worker_1  | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.3:3306
syncing-server-js-worker_1  | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.3:3306
syncing-server-js-worker_1  | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.3:3306
syncing-server-js-worker_1  | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.3:3306
syncing-server-js-worker_1  | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.3:3306
syncing-server-js-worker_1  | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.3:3306
syncing-server-js-worker_1  | /var/www/node_modules/mysql2/lib/pool_cluster.js:36
syncing-server-js-worker_1  |       return cb(new Error('Pool does Not exists.'));
syncing-server-js-worker_1  |                 ^
syncing-server-js-worker_1  |
syncing-server-js-worker_1  | Error: Pool does Not exists.
syncing-server-js-worker_1  |     at PoolNamespace.getConnection (/var/www/node_modules/mysql2/lib/pool_cluster.js:36:17)
syncing-server-js-worker_1  |     at /var/www/node_modules/mysql2/lib/pool_cluster.js:43:21
syncing-server-js-worker_1  |     at /var/www/node_modules/mysql2/lib/pool_cluster.js:210:18
syncing-server-js-worker_1  |     at /var/www/node_modules/mysql2/lib/pool.js:60:18
syncing-server-js-worker_1  |     at PoolConnection.<anonymous> (/var/www/node_modules/mysql2/lib/connection.js:739:13)
syncing-server-js-worker_1  |     at Object.onceWrapper (node:events:485:26)
syncing-server-js-worker_1  |     at PoolConnection.emit (node:events:390:22)
syncing-server-js-worker_1  |     at PoolConnection.EventEmitter.emit (node:domain:470:12)
syncing-server-js-worker_1  |     at PoolConnection._notifyError (/var/www/node_modules/mysql2/lib/connection.js:225:12)
syncing-server-js-worker_1  |     at PoolConnection._handleFatalError (/var/www/node_modules/mysql2/lib/connection.js:156:10)
syncing-server-js-worker_1  | error Command failed with exit code 1.
syncing-server-js-worker_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
standalone_syncing-server-js-worker_1 exited with code 1
```

Eventually gets to this point in repeat:
```
auth-worker_1               | nc: bad address 'auth'
auth-worker_1               | auth:3000 is unavailable yet - waiting for it to start
api-gateway_1               | nc: bad address 'auth'
api-gateway_1               | auth:3000 is unavailable yet - waiting for it to start
syncing-server-js-worker_1  | [Error] PoolCluster : Error: getaddrinfo EAI_AGAIN db
syncing-server-js-worker_1  | [Error] PoolCluster : Error: getaddrinfo EAI_AGAIN db
```

I've tried changing the `NODE_ENV` to production, but no change.

Any ideas?

Also, in the .env file, the `NEW_RELIC_APP_NAME` has spaces, which caused issues in the beginning for me, so I added underscores.
```
NEW_RELIC_APP_NAME=Syncing_Server_JS
```

**Comment by mobitar** [comment]
Karol can check in on this on Monday. In the meantime, my guess is that this is a DB credential issue. Can you share your full .env, redacting any sensitive values?

**Comment by joshcsullivan** [comment]
Here is my current .env file:
```
LOG_LEVEL=info
NODE_ENV=production

JWT_SECRET=SECRET
LEGACY_JWT_SECRET=SECRET
AUTH_JWT_SECRET=SECRET

EXPOSED_PORT=8080

DB_HOST=db
DB_REPLICA_HOST=db
DB_PORT=3306
DB_USERNAME=std_notes_user
DB_PASSWORD=SECRET
DB_DATABASE=standard_notes_db
DB_DEBUG_LEVEL=all # "all" | "query" | "schema" | "error" | "warn" | "info" | "log" | "migration"
DB_MIGRATIONS_PATH=dist/migrations/*.js

REDIS_URL=redis://cache

DISABLE_USER_REGISTRATION=false

ACCESS_TOKEN_AGE=5184000
REFRESH_TOKEN_AGE=31556926

EPHEMERAL_SESSION_AGE=259200

MAX_LOGIN_ATTEMPTS=6
FAILED_LOGIN_LOCKOUT=3600

PSEUDO_KEY_PARAMS_KEY=secret_key

SNS_TOPIC_ARN=
SNS_AWS_REGION=
SQS_QUEUE_URL=
SQS_AWS_REGION=
S3_AWS_REGION=
S3_BACKUP_BUCKET_NAME=

USER_SERVER_REGISTRATION_URL=
USER_SERVER_AUTH_KEY=

REDIS_EVENTS_CHANNEL=events

INTERNAL_DNS_REROUTE_ENABLED=false
EXTENSIONS_SERVER_URL=http://extensions-server:3004
AUTH_SERVER_URL=http://auth:3000

EMAIL_ATTACHMENT_MAX_BYTE_SIZE=10485760

REVISIONS_FREQUENCY=300

# (Optional) New Relic Setup
NEW_RELIC_ENABLED=false
NEW_RELIC_APP_NAME=Syncing_Server_JS
NEW_RELIC_LICENSE_KEY=
NEW_RELIC_NO_CONFIG_FILE=true
NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=false
NEW_RELIC_LOG_ENABLED=false
NEW_RELIC_LOG_LEVEL=info
```

**Comment by karolsojko** [comment]
So it seems from your logs that `syncing-server-js-worker_1` was trying to start before the database service was available, thus the error.

I've applied a fix where all services will wait for the db to be available now. Although it may not fix your issue entirely, we might see some more insight in logs on why the db did not start.

Can you try updating your setup with `./server.sh update` ?

**Comment by joshcsullivan** [comment]
The fix, did fix the `syncing-server-js-worker_1` issue, but after that I get these continuously:
```
auth-worker_1               | nc: bad address 'auth'
api-gateway_1               | nc: bad address 'auth'
auth-worker_1               | auth:3000 is unavailable yet - waiting for it to start
api-gateway_1               | auth:3000 is unavailable yet - waiting for it to start
```

When looking for auth in the logs, I find this:
```
auth_1                      | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.8:3306
auth_1                      | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.8:3306
auth_1                      | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.8:3306
auth_1                      | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.8:3306
auth_1                      | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.8:3306
auth_1                      | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.8:3306
auth_1                      | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.8:3306
auth_1                      | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.8:3306
auth_1                      | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.8:3306
auth_1                      | [Error] PoolCluster : Error: connect ECONNREFUSED 172.19.0.8:3306
auth_1                      | /var/www/node_modules/mysql2/lib/pool_cluster.js:36
auth_1                      |       return cb(new Error('Pool does Not exists.'));
auth_1                      |                 ^
auth_1                      |
auth_1                      | Error: Pool does Not exists.
auth_1                      |     at PoolNamespace.getConnection (/var/www/node_modules/mysql2/lib/pool_cluster.js:36:17)
auth_1                      |     at /var/www/node_modules/mysql2/lib/pool_cluster.js:43:21
auth_1                      |     at /var/www/node_modules/mysql2/lib/pool_cluster.js:210:18
auth_1                      |     at /var/www/node_modules/mysql2/lib/pool.js:60:18
auth_1                      |     at PoolConnection.<anonymous> (/var/www/node_modules/mysql2/lib/connection.js:739:13)
auth_1                      |     at Object.onceWrapper (node:events:485:26)
auth_1                      |     at PoolConnection.emit (node:events:390:22)
auth_1                      |     at PoolConnection.EventEmitter.emit (node:domain:470:12)
auth_1                      |     at PoolConnection._notifyError (/var/www/node_modules/mysql2/lib/connection.js:225:12)
auth_1                      |     at PoolConnection._handleFatalError (/var/www/node_modules/mysql2/lib/connection.js:156:10)
auth_1                      | error Command failed with exit code 1.
auth_1                      | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
standalone_auth_1 exited with code 1
standalone_db_1 exited with code 137
```

**Comment by karolsojko** [comment]
Based on this: https://github.com/standardnotes/standalone/blob/main/docker-compose.yml#L49

`auth` should wait on `db` to start.

Can you provide us with more logs, especially what happened to the `db` service if you scroll up ?

**Comment by karolsojko** [comment]
as a last resort if you don't have any data in the setup yet you can try `./server.sh cleanup` but please be aware this wipes out all the db data

**Comment by joshcsullivan** [comment]
I've used the ./server.sh cleanup after every change (stopping it first of course), because there is no data there.

Here is the full log output:

[Logs.txt](https://github.com/standardnotes/standalone/files/6502828/Logs.txt)

**Comment by karolsojko** [comment]
@joshcsullivan can you do `./server.sh update && ./server.sh cleanup` and then start the setup? 

Also please check if you have proper env vars set up, docs: https://docs.standardnotes.org/self-hosting/configuration-options/

especially

**Comment by joshcsullivan** [comment]
I tried those instructions, but the same issue was occurring.

Spun up a new VM and had no problems with setting up the server, so I think it was something specific with that VM.

Thanks for trying to fix this with me.
