### ISSUE TITLE
Odd issue with auth

### ISSUE THREAD

**Issue by firestrife23** [standardnotes/standalone#14]
I use docker compose to spin up standalone, but auth is hung up with error and rebooting itself... 

Log:

```
db (172.31.0.29:3306) open
db:3306 is up - executing command
cache (172.31.0.28:6379) open
cache:6379 is up - executing command
syncing-server-js:3000 is unavailable yet - waiting for it to start
syncing-server-js:3000 is unavailable yet - waiting for it to start
syncing-server-js (172.31.0.30:3000) open
syncing-server-js:3000 is up - executing command
Starting Web...
yarn run v1.22.5
$ node dist/bin/server.js
{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"34be9a3cb30c","pid":36,"time":"2021-06-21T05:46:32.846Z","msg":"NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables."}
{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"34be9a3cb30c","pid":36,"time":"2021-06-21T05:46:34.122Z","msg":"NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables."}
[Error] PoolCluster : Error: getaddrinfo ENOTFOUND  db
[Error] PoolCluster : Error: getaddrinfo ENOTFOUND  db
[Error] PoolCluster : Error: getaddrinfo ENOTFOUND  db
[Error] PoolCluster : Error: getaddrinfo ENOTFOUND  db
[Error] PoolCluster : Error: getaddrinfo ENOTFOUND  db
[Error] PoolCluster : Error: getaddrinfo ENOTFOUND  db
[Error] PoolCluster : Error: getaddrinfo ENOTFOUND  db
[Error] PoolCluster : Error: getaddrinfo ENOTFOUND  db
[Error] PoolCluster : Error: getaddrinfo ENOTFOUND  db
[Error] PoolCluster : Error: getaddrinfo ENOTFOUND  db
/var/www/node_modules/mysql2/lib/pool_cluster.js:36
      return cb(new Error('Pool does Not exists.'));
                ^
Error: Pool does Not exists.
    at PoolNamespace.getConnection (/var/www/node_modules/mysql2/lib/pool_cluster.js:36:17)
    at /var/www/node_modules/mysql2/lib/pool_cluster.js:43:21
    at /var/www/node_modules/mysql2/lib/pool_cluster.js:210:18
    at /var/www/node_modules/mysql2/lib/pool.js:60:18
    at PoolConnection.<anonymous> (/var/www/node_modules/mysql2/lib/connection.js:739:13)
    at Object.onceWrapper (node:events:485:26)
    at PoolConnection.emit (node:events:390:22)
    at PoolConnection.EventEmitter.emit (node:domain:470:12)
    at PoolConnection._notifyError (/var/www/node_modules/mysql2/lib/connection.js:225:12)
    at PoolConnection._handleFatalError (/var/www/node_modules/mysql2/lib/connection.js:156:10)
error Command failed with exit code 1.
```

As you can see at the beginning the "db" is reachable however at the bottom showing server.js is having trouble resolving "db" I even tried running nslookup within auth container and resolved "db" just fine... I'm not sure where to go from here.

**Comment by JaspalSuri** [comment]
I apologize in advance if this is irrelevant as I'm not a dev, but are you using the Snap version of Docker by any chance? Some users have reported having issues with it.

**Comment by firestrife23** [comment]
I'm using docker's official repository for Debian/Ubuntu.

**Comment by firestrife23** [comment]
any update? I still can't use standardnotes.

**Comment by mobitar** [comment]
Can you pull latest changes on standalone, run `./server.sh update`, and try launching again? We've been making changes fast so it could be your issue was fixed along the way.

If not, please include your .env file and latest logs.

**Comment by firestrife23** [comment]
It's now working with the latest pull, and thank you very much.
