### ISSUE TITLE
[BUG] ...

### ISSUE THREAD

**Issue by joekerna** [standardnotes/standalone#25]
I followed the guide to self host standardnotes including the migration from the legacy server.

**Logs**
The logfile says
`syncing-server-js_1         | {"message":"Server started on port 3000","level":"info"}`
`db_1                        | Version: '5.6.51'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)`
Healthcheck says `OK`

But when I access `http://localhost:3000` I get

`Cannot GET /`

Can someone help me debug? I don't really know where else to look.

Thanks a lot

**Comment by eric-pierce** [comment]
Hey @joekerna, the new architecture only intends for the api-gateway container to be publicly accessible, and for it to talk to the auth and syncing-server containers internally. 

Assuming you have the api-gateway container configured and live, you should be hitting http://localhost:3000/healthcheck to validate the health status of the endpoint.

More details on that piece of the setup are here: https://docs.standardnotes.org/self-hosting/docker/

**Comment by joekerna** [comment]
Health status is `OK`.

But when I try to log into the server using the web interface (3.8.17) I get
`Invalid email or password`

Is there a way to check, if the DB import has succeeded?

If I try to register a new account I get
`Unknown error`

**Comment by joekerna** [comment]
In the legacy version I was using a locally running instance of MySQL (not docker). Is that still possible? That one still has the database.

I remeber changing `DB_HOST` to `127.0.0.1`

**Comment by eric-pierce** [comment]
@joekerna would you provide the logs of the api-gateway, auth, and syncing-server containers when you try to login from the web ui? 

Also this may be simple but I have made this mistake in the past - have you confirmed that your web ui is pointing to your server and not the standardnotes hosted server (https://api.standardnotes.com)?

**Comment by joekerna** [comment]
This is the log when I try to log in from the web-app (I changed my eMail address, the server name was correct):
```

auth_1                      | query: SELECT `user`.`uuid` AS `user_uuid`, `user`.`version` AS `user_version`, `user`.`email` AS `user_email`, `user`.`pw_nonce` AS `user_pw_nonce`, `user`.`encrypted_server_key` AS `user_encrypted_server
_key`, `user`.`server_encryption_version` AS `user_server_encryption_version`, `user`.`kp_created` AS `user_kp_created`, `user`.`kp_origination` AS `user_kp_origination`, `user`.`pw_cost` AS `user_pw_cost`, `user`.`pw_key_size` AS `use
r_pw_key_size`, `user`.`pw_salt` AS `user_pw_salt`, `user`.`pw_alg` AS `user_pw_alg`, `user`.`pw_func` AS `user_pw_func`, `user`.`encrypted_password` AS `user_encrypted_password`, `user`.`created_at` AS `user_created_at`, `user`.`updat
ed_at` AS `user_updated_at`, `user`.`locked_until` AS `user_locked_until`, `user`.`num_failed_attempts` AS `user_num_failed_attempts`, `user`.`updated_with_user_agent` AS `user_updated_with_user_agent` FROM `users` `user` WHERE `user`.
`email` = ? -- PARAMETERS: ["MY@EMAIL.COM"]                                                                                                                                                                                       
auth_1                      | query: SELECT `user`.`uuid` AS `user_uuid`, `user`.`version` AS `user_version`, `user`.`email` AS `user_email`, `user`.`pw_nonce` AS `user_pw_nonce`, `user`.`encrypted_server_key` AS `user_encrypted_server
_key`, `user`.`server_encryption_version` AS `user_server_encryption_version`, `user`.`kp_created` AS `user_kp_created`, `user`.`kp_origination` AS `user_kp_origination`, `user`.`pw_cost` AS `user_pw_cost`, `user`.`pw_key_size` AS `use
r_pw_key_size`, `user`.`pw_salt` AS `user_pw_salt`, `user`.`pw_alg` AS `user_pw_alg`, `user`.`pw_func` AS `user_pw_func`, `user`.`encrypted_password` AS `user_encrypted_password`, `user`.`created_at` AS `user_created_at`, `user`.`updat
ed_at` AS `user_updated_at`, `user`.`locked_until` AS `user_locked_until`, `user`.`num_failed_attempts` AS `user_num_failed_attempts`, `user`.`updated_with_user_agent` AS `user_updated_with_user_agent` FROM `users` `user` WHERE `user`.
`email` = ? -- PARAMETERS: ["MY@EMAIL.COM"]                                                                                                                                                                                       
auth_1                      | query: SELECT `user`.`uuid` AS `user_uuid`, `user`.`version` AS `user_version`, `user`.`email` AS `user_email`, `user`.`pw_nonce` AS `user_pw_nonce`, `user`.`encrypted_server_key` AS `user_encrypted_server
_key`, `user`.`server_encryption_version` AS `user_server_encryption_version`, `user`.`kp_created` AS `user_kp_created`, `user`.`kp_origination` AS `user_kp_origination`, `user`.`pw_cost` AS `user_pw_cost`, `user`.`pw_key_size` AS `use
r_pw_key_size`, `user`.`pw_salt` AS `user_pw_salt`, `user`.`pw_alg` AS `user_pw_alg`, `user`.`pw_func` AS `user_pw_func`, `user`.`encrypted_password` AS `user_encrypted_password`, `user`.`created_at` AS `user_created_at`, `user`.`updat
ed_at` AS `user_updated_at`, `user`.`locked_until` AS `user_locked_until`, `user`.`num_failed_attempts` AS `user_num_failed_attempts`, `user`.`updated_with_user_agent` AS `user_updated_with_user_agent` FROM `users` `user` WHERE `user`.
`email` = ? -- PARAMETERS: ["MY@EMAIL.COM"]                                                                                                                                                                                       
auth_1                      | query: SELECT `user`.`uuid` AS `user_uuid`, `user`.`version` AS `user_version`, `user`.`email` AS `user_email`, `user`.`pw_nonce` AS `user_pw_nonce`, `user`.`encrypted_server_key` AS `user_encrypted_server
_key`, `user`.`server_encryption_version` AS `user_server_encryption_version`, `user`.`kp_created` AS `user_kp_created`, `user`.`kp_origination` AS `user_kp_origination`, `user`.`pw_cost` AS `user_pw_cost`, `user`.`pw_key_size` AS `use
r_pw_key_size`, `user`.`pw_salt` AS `user_pw_salt`, `user`.`pw_alg` AS `user_pw_alg`, `user`.`pw_func` AS `user_pw_func`, `user`.`encrypted_password` AS `user_encrypted_password`, `user`.`created_at` AS `user_created_at`, `user`.`updat
ed_at` AS `user_updated_at`, `user`.`locked_until` AS `user_locked_until`, `user`.`num_failed_attempts` AS `user_num_failed_attempts`, `user`.`updated_with_user_agent` AS `user_updated_with_user_agent` FROM `users` `user` WHERE `user`.
`email` = ? -- PARAMETERS: ["MY@EMAIL.COM"]                                                                                                                                                                                       
auth_1                      | query: SELECT `user`.`uuid` AS `user_uuid`, `user`.`version` AS `user_version`, `user`.`email` AS `user_email`, `user`.`pw_nonce` AS `user_pw_nonce`, `user`.`encrypted_server_key` AS `user_encrypted_server
_key`, `user`.`server_encryption_version` AS `user_server_encryption_version`, `user`.`kp_created` AS `user_kp_created`, `user`.`kp_origination` AS `user_kp_origination`, `user`.`pw_cost` AS `user_pw_cost`, `user`.`pw_key_size` AS `use
r_pw_key_size`, `user`.`pw_salt` AS `user_pw_salt`, `user`.`pw_alg` AS `user_pw_alg`, `user`.`pw_func` AS `user_pw_func`, `user`.`encrypted_password` AS `user_encrypted_password`, `user`.`created_at` AS `user_created_at`, `user`.`updat
ed_at` AS `user_updated_at`, `user`.`locked_until` AS `user_locked_until`, `user`.`num_failed_attempts` AS `user_num_failed_attempts`, `user`.`updated_with_user_agent` AS `user_updated_with_user_agent` FROM `users` `user` WHERE `user`.
`email` = ? -- PARAMETERS: ["MY@EMAIL.COM"]                                                                                                                                                                                       
auth_1                      | query: SELECT `user`.`uuid` AS `user_uuid`, `user`.`version` AS `user_version`, `user`.`email` AS `user_email`, `user`.`pw_nonce` AS `user_pw_nonce`, `user`.`encrypted_server_key` AS `user_encrypted_server
_key`, `user`.`server_encryption_version` AS `user_server_encryption_version`, `user`.`kp_created` AS `user_kp_created`, `user`.`kp_origination` AS `user_kp_origination`, `user`.`pw_cost` AS `user_pw_cost`, `user`.`pw_key_size` AS `use
r_pw_key_size`, `user`.`pw_salt` AS `user_pw_salt`, `user`.`pw_alg` AS `user_pw_alg`, `user`.`pw_func` AS `user_pw_func`, `user`.`encrypted_password` AS `user_encrypted_password`, `user`.`created_at` AS `user_created_at`, `user`.`updat
ed_at` AS `user_updated_at`, `user`.`locked_until` AS `user_locked_until`, `user`.`num_failed_attempts` AS `user_num_failed_attempts`, `user`.`updated_with_user_agent` AS `user_updated_with_user_agent` FROM `users` `user` WHERE `user`.
`email` = ? -- PARAMETERS: ["MY@EMAIL.COM"]                                                                                              
```                                                                                                

This is what I get, when I try to register a new user:

```
auth_1                      | query: SELECT `user`.`uuid` AS `user_uuid`, `user`.`version` AS `user_version`, `user`.`email` AS `user_email`, `user`.`pw_nonce` AS `user_pw_nonce`, `user`.`encrypted_server_key` AS `user_encrypted_server
_key`, `user`.`server_encryption_version` AS `user_server_encryption_version`, `user`.`kp_created` AS `user_kp_created`, `user`.`kp_origination` AS `user_kp_origination`, `user`.`pw_cost` AS `user_pw_cost`, `user`.`pw_key_size` AS `use
r_pw_key_size`, `user`.`pw_salt` AS `user_pw_salt`, `user`.`pw_alg` AS `user_pw_alg`, `user`.`pw_func` AS `user_pw_func`, `user`.`encrypted_password` AS `user_encrypted_password`, `user`.`created_at` AS `user_created_at`, `user`.`updat
ed_at` AS `user_updated_at`, `user`.`locked_until` AS `user_locked_until`, `user`.`num_failed_attempts` AS `user_num_failed_attempts`, `user`.`updated_with_user_agent` AS `user_updated_with_user_agent` FROM `users` `user` WHERE `user`.
`email` = ? -- PARAMETERS: ["bla@blub.com"]                                                                                                                                                                                                
auth_1                      | query: SELECT `role`.`uuid` AS `role_uuid`, `role`.`name` AS `role_name`, `role`.`created_at` AS `role_created_at`, `role`.`updated_at` AS `role_updated_at` FROM `roles` `role` WHERE `role`.`name` = ? -- P
ARAMETERS: ["USER"]                                                                                                                                                                                                                        
auth_1                      | query failed: SELECT `role`.`uuid` AS `role_uuid`, `role`.`name` AS `role_name`, `role`.`created_at` AS `role_created_at`, `role`.`updated_at` AS `role_updated_at` FROM `roles` `role` WHERE `role`.`name` =
 ? -- PARAMETERS: ["USER"]                                                                                                                                                                                                                 
auth_1                      | error: Error: Table 'standard_notes_db.roles' doesn't exist
auth_1                      |     at Packet.asError (/var/www/node_modules/mysql2/lib/packets/packet.js:712:17)
auth_1                      |     at Query.execute (/var/www/node_modules/mysql2/lib/commands/command.js:28:26)
auth_1                      |     at PoolConnection.handlePacket (/var/www/node_modules/mysql2/lib/connection.js:425:32)
auth_1                      |     at PacketParser.onPacket (/var/www/node_modules/mysql2/lib/connection.js:75:12)
auth_1                      |     at PacketParser.executeStart (/var/www/node_modules/mysql2/lib/packet_parser.js:75:16)
auth_1                      |     at Socket.<anonymous> (/var/www/node_modules/mysql2/lib/connection.js:82:25)
auth_1                      |     at Socket.emit (node:events:378:20)
auth_1                      |     at Socket.EventEmitter.emit (node:domain:470:12)
auth_1                      |     at addChunk (node:internal/streams/readable:313:12)
auth_1                      |     at readableAddChunk (node:internal/streams/readable:288:9) {
auth_1                      |   code: 'ER_NO_SUCH_TABLE',
auth_1                      |   errno: 1146,
auth_1                      |   sqlState: '42S02',
auth_1                      |   sqlMessage: "Table 'standard_notes_db.roles' doesn't exist"
auth_1                      | }
auth_1                      | QueryFailedError: Table 'standard_notes_db.roles' doesn't exist
auth_1                      |     at new QueryFailedError (/var/www/node_modules/typeorm/error/QueryFailedError.js:11:28)
auth_1                      |     at Query.onResult (/var/www/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:216:45)
auth_1                      |     at Query.execute (/var/www/node_modules/mysql2/lib/commands/command.js:30:14)
auth_1                      |     at PoolConnection.handlePacket (/var/www/node_modules/mysql2/lib/connection.js:425:32)
auth_1                      |     at PacketParser.onPacket (/var/www/node_modules/mysql2/lib/connection.js:75:12)
auth_1                      |     at PacketParser.executeStart (/var/www/node_modules/mysql2/lib/packet_parser.js:75:16)
auth_1                      |     at Socket.<anonymous> (/var/www/node_modules/mysql2/lib/connection.js:82:25)
auth_1                      |     at Socket.emit (node:events:378:20)
auth_1                      |     at Socket.EventEmitter.emit (node:domain:470:12)
auth_1                      |     at addChunk (node:internal/streams/readable:313:12)
api-gateway_1               | {"message":"Could not pass the request to underlying services: undefined","level":"error"}        
```

**Comment by mobitar** [comment]
> But when I access http://localhost:3000 I get Cannot GET /

You shouldn't access it in the browser. This is only an API, so try signing in using the desktop app and plugging in your server URL.

**Comment by joekerna** [comment]
Now I know that. But even the login from the webapp or phone does not work as desribed above

**Comment by eric-pierce** [comment]
@joekerna it doesn't look like your database has updated as new tables like "roles" are missing - here's the old database schema vs the new one:
![image](https://user-images.githubusercontent.com/551464/126362983-586659ad-50fd-490b-921b-884213d8fe5c.png)

Did you go through the database migration steps listed here: https://docs.standardnotes.org/self-hosting/legacy-migration/ ?

I'd take a dump of the old database and then rename it to something like snbackup (as I did in the screenshot), and allow the server container to create a new database. The new database should have the correct tables, then you can import the dump you took of the old one to re-populate your data.

**Comment by joekerna** [comment]
I've created a database dump
Then I executed 
`git clone --single-branch --branch main https://github.com/standardnotes/standalone.git .`
`./server.sh setup`

I changed `AUTH_JWT_SECRET `and `DB_PASSWORD `in `.env`
I changed `JWT_SECRET`, `LEGACY_JWT_SECRET `and `ENCRYPTION_SERVER_KEY `in `docker/auth.env`

I copied my database dump to `data/import`

Then I executed `./server.sh start`

`curl http://localhost:3000/healthcheck` says `OK`

But I can't log in or create a new user

**Comment by ey-tsifry** [comment]
FWIW it doesn't look like the health check really involves interfacing with the DB (https://github.com/standardnotes/syncing-server-js/blob/main/src/Controller/HealthCheckController.ts).  Its purpose seems more to indicate whether the endpoint route successfully returns a response for a HTTP GET request.

Regarding the database issue, a few other things you may want to check  in `.env` are:
1. Is `DB_USERNAME` set to the DB username you were using before?
2. Is `DB_PASSWORD` set to the DB password you were using before?
3. Is `DB_DATABASE` set to the correct DB database name?  (this may or may not be *different* to the DB name you used before.  The legacy syncing-server may have used a different naming scheme)

I'm not sure if the old MySQL user was preserved in your DB dump (it depends on whether you dumped the `mysql` table) or if standalone just creates a new MySQL user if it doesn't already exist. If these were preserved, check the above list first.  If they weren't preserved, see  `Other things to check` below.

In `docker/auth.env`, also check:
1. Is `DISABLE_USER_REGISTRATION` set to `false`?

Other things to check:
* Does your DB user exist in the new database?  You can test this by trying to log in to the DB manually with the user: `sudo docker exec -it <db_container_name> mysql -u <db_username> -p`
* Does your DB user have the right privileges for the right DB to insert, drop, alter, etc?
* In the UI, are you logging into your server instead of api.standardnotes.com?

**Comment by joekerna** [comment]
I will try that once I find time.
One other question though: I used to connect to a MySQL instance running outside of docker. Can I still do that? Because that database used to work perfectly with the legacy syncing server

**Comment by joekerna** [comment]
I logged into my MySQL database, which I used with the legacy server.
The user and the database exist, The privileges seem to be there:

> GRANT ALL PRIVILEGES ON `standard_notes_db`.* TO `std_notes_user`@`localhost`

In `.env` I changed `DB` and `DB_REPLICA_HOST` to `127.0.0.1`

The logfile says a lot of messages like

> 
> [Error] PoolCluster : Error: connect ECONNREFUSED 127.0.0.1:3306
> syncing-server-js_1         | [Error] PoolCluster : Error: connect ECONNREFUSED 127.0.0.1:3306
> syncing-server-js_1         | /var/www/node_modules/mysql2/lib/pool_cluster.js:36
> syncing-server-js_1         |       return cb(new Error('Pool does Not exists.'));

**Comment by ey-tsifry** [comment]
1. If you're using the Docker MySQL, port 3306 is not the port that is exposed on the host by default, nor is the actual container port bound to 127.0.0.1.  So that's why 127.0.0.1:3306 doesn't work in this particular circumstance.  Here's the relevant output from `docker container ls` and `sudo netstat -nap`:

```
CONTAINER ID   IMAGE                                    COMMAND                  CREATED        STATUS        PORTS                                NAMES
xxxxxxxxxxxx   mysql:5.7                                "docker-entrypoint.s…"   X hours ago   Up X hours   33060/tcp, 0.0.0.0:49156->3306/tcp   standalone_db_1

Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:49156           0.0.0.0:*               LISTEN      8245/docker-proxy
```

(Note that the port after `0.0.0.0` is randomly assigned, so you probably shouldn't hard code that anywhere).

For this docker setup, I believe that you also want `DB` and `DB_REPLICA_HOST` to reference the actual `db` entry in `docker-compose.yml` rather than a literal host or IP.

2. Related to the above, try creating a new `'std_notes'@'%'` user instead.  Docker MySQL doesn't see a connection from `syncing-server-js_1` as a connection from `localhost` right now, hence the need for a wildcard instead.

The end result should look similar to:
```
mysql> select User, Host from user where user = 'std_notes';
+-----------+------+
| User      | Host |
+-----------+------+
| std_notes | %    |
+-----------+------+
1 row in set (0.00 sec)

mysql> SHOW GRANTS FOR 'std_notes'@'%';
+----------------------------------------------------------------+
| Grants for std_notes@%                                         |
+----------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'std_notes'@'%'                          |
| GRANT ALL PRIVILEGES ON `standard\_notes`.* TO 'std_notes'@'%' |
+----------------------------------------------------------------+
2 rows in set (0.00 sec)
```

Alternatively you could explicitly map the host and container ports in `docker-compose.yml`:
```
  db:
    [...]
    ports:
      - 3306:3306
```

**Comment by joekerna** [comment]
I am still struggling. With an updated docker image I can now create new users but the old ones with all their notes are still missing.

I've accessed the database in the docker container. It is there but the `users` table is empty.

> mysql> select * from users;
> Empty set (0.00 sec)

I guess the import has failed. Is it possible to trigger the import again manually? Or where should I look the quite lengthy docker logs?

**Comment by mobitar** [comment]
At this point I might just manually import using a MySQL client. Open the old DB, export as SQL, open new DB, run the SQL.

**Comment by ey-tsifry** [comment]
Hmm, I'll provide a few examples from my personal experience with manual Standard Notes MySQL DB migration in case it can be of use here.

As background I've now manually migrated my database a few different times, first from the non-Dockerized standard_file to Dockerized standard_notes_db, and later between Dockerized DBs on different hosts and on the same host.  I performed all of these migrations before the related documentation existed on docs.standardnotes.org, so it was good times all around. :->

Here are a few methods that I've used, sorted from low to high according to level of pain:


### 1. Minimal touch / minimal effort option  ###

This option is only useful if you are the only user on your server.  It doesn't scale well beyond that.

1. [**Client**] Open your *Standard Notes* client, go to **Account** and **download** a backup of your data to a local file
2. [**Server**] Start a fresh Standalone server with applicable config settings and an empty database
3. [**Client**] Register your user on the server and log in
4. [**Client**] Go to **Account** and **import** the backup file that you exported earlier
	* (depending on the amount of data, it may take a while for everything to fully upload to the server)
5. Profit

### 2. Dump old DB to SQL file, then let Docker import it ###

1. [**Server**] Dump existing MySQL standard_notes DB to a SQL file
	* Follow the instructions on https://docs.standardnotes.org/self-hosting/legacy-migration/
2. [**Server**] Copy the SQL file to `path-to-your-standalone/data/import`
3. [**Server**] Verify that the following config stanza is in the `docker-compose.yml` *db* section:
  ```
      volumes:
        - ./data:/var/lib/mysql
        - ./data/import:/docker-entrypoint-initdb.d
  ```

> **IMPORTANT**: If `./data` (first line) is **not** empty of database files, then the MySQL file in `./data/import` (second line) will **not** be executed.  If the import isn't working, then stop the server, try deleting everything in `./data` except `import/*`, and start the server again to re-trigger the import.

4. [**Server**] Start the server
5. [**Server** / **Client**] Verify that the data has been imported
	* **Server**: You can verify this quickly on the host by checking `./data` for a directory that corresponds with the name of your database.  Check that there are table files of plausible size in `./data/<DATABASE_NAME>`.
6. Profit


### 3. Dump old DB to SQL file, then manually import it with the MySQL client ###

1. [**Server**] Dump existing MySQL standard_notes DB to a SQL file
	* Follow the instructions on https://docs.standardnotes.org/self-hosting/legacy-migration/
2. [**Server**] Make sure that the DB container is running
3. [**Server**] Manually connect to the Docker MySQL client: `sudo docker exec -it <DB_CONTAINER_ID> mysql -u root -p`
4. [**Docker MySQL client**] Create the database: `create database <DATABASE_NAME>;`
5. [**Docker MySQL client**] (if needed) You might also have to manually create the standard notes user:
```
CREATE USER '<STD_NOTES_USER>'@'%' IDENTIFIED WITH mysql_native_password BY '<PASSWORD>';
GRANT ALL ON <DATABASE_NAME>.* TO '<STD_NOTES_USER>'@'%';
```
6. [**Docker MySQL client**] Log out of the MySQL client: `quit;`
7. [**Server**] Import the SQL file that you dumped earlier:
```
sudo docker exec -it <DB_CONTAINER_ID> mysql -u root -p <DATABASE_NAME> < <SQL_FILE>
```
8. [**Server** / **Client**] Verify that the data has been imported
9. Profit

Enjoy (?), and hopefully this helps.

**Comment by joekerna** [comment]
Thanks a lot for the very detailled description! I'll go with option 3. When trying to connec to the MySQL client, what is the password for root? Did I set that somewhere? I get
`ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)`

**Comment by ey-tsifry** [comment]
https://stackoverflow.com/questions/2995054/access-denied-for-user-rootlocalhost-using-passwordno

https://dev.mysql.com/doc/refman/5.6/en/default-privileges.html
https://dev.mysql.com/doc/refman/5.7/en/default-privileges.html

**Comment by joekerna** [comment]
When trying to manually import the database I get the following error:

> ERROR 1273 (HY000) at line 78: Unknown collation: 'utf8mb4_0900_ai_ci'  

The tables above line 78 in the dbdump are imported, everything below is not.

After changing _utf8mb4_0900_ai_ci_ to _utf8mb4_general_ci_ ([link](https://stackoverflow.com/questions/42385099/1273-unknown-collation-utf8mb4-unicode-520-ci/44122258#44122258)) the database now contains 10 tables

+-----------------------------+                                                                                                                                                                          
| Tables_in_standard_notes_db |                                                                                                                                                                          
+-----------------------------+                                                                                                                                                                          
| ar_internal_metadata   |                                                                                                                                                                          
| extension_settings       |                                                                                                                                                                          
| item_revisions               |                                                                                                                                                                          
| items                              |                                                                                                                                                                          
| migrations                     |                                                                                                                                                                          
| revisions                        |                                                                                                                                                                          
| revoked_sessions          |                                                                                                                                                                          
| schema_migrations      |                                                                                                                                                                          
| sessions                        |                                                                                                                                                                            
| users                             |                                                                                                                                                                          
+-----------------------------+              

How do I get the server to update the schema to the new one?

I thought maybe the user does not have priviliges do modify the database but it looks correct to me:

+---------------------------------------------------------------------------------------------------------------+                                                                                        
| Grants for std_notes_user@%                                                                                   |                                                                                        
+---------------------------------------------------------------------------------------------------------------+                                                                                        
| GRANT USAGE ON *.* TO 'std_notes_user'@'%' IDENTIFIED BY PASSWORD '*...' |                                                                                        
| GRANT ALL PRIVILEGES ON `standard\_notes\_db`.* TO 'std_notes_user'@'%'                                       |                                                                                        
+---------------------------------------------------------------------------------------------------------------+

**Comment by joekerna** [comment]
I've noticed a few error messages like this

> auth                        | query: START TRANSACTION
> auth                        | query: ALTER TABLE `revoked_sessions` ADD CONSTRAINT `FK_b357d1397b82bcda5e6cc9b0062` FOREIGN KEY (`user_uuid`) REFERENCES `users`(`uuid`) ON DELETE CASCADE ON UPDATE NO A
> CTION                                                                                                                                                                                                    
> auth                        | query failed: ALTER TABLE `revoked_sessions` ADD CONSTRAINT `FK_b357d1397b82bcda5e6cc9b0062` FOREIGN KEY (`user_uuid`) REFERENCES `users`(`uuid`) ON DELETE CASCADE ON UPDA
> TE NO ACTION                                                                                                                                                                                             
> auth                        | error: Error: Cannot add foreign key constraint
> auth                        |     at Packet.asError (/var/www/node_modules/mysql2/lib/packets/packet.js:712:17)
> auth                        |     at Query.execute (/var/www/node_modules/mysql2/lib/commands/command.js:28:26)
> auth                        |     at PoolConnection.handlePacket (/var/www/node_modules/mysql2/lib/connection.js:425:32)
> auth                        |     at PacketParser.onPacket (/var/www/node_modules/mysql2/lib/connection.js:75:12)
> auth                        |     at PacketParser.executeStart (/var/www/node_modules/mysql2/lib/packet_parser.js:75:16)
> auth                        |     at Socket.<anonymous> (/var/www/node_modules/mysql2/lib/connection.js:82:25)
> auth                        |     at Socket.emit (node:events:378:20)
> auth                        |     at Socket.EventEmitter.emit (node:domain:470:12)
> auth                        |     at addChunk (node:internal/streams/readable:313:12)
> auth                        |     at readableAddChunk (node:internal/streams/readable:288:9) {
> auth                        |   code: 'ER_CANNOT_ADD_FOREIGN',
> auth                        |   errno: 1215,
> auth                        |   sqlState: 'HY000',
> auth                        |   sqlMessage: 'Cannot add foreign key constraint'
> auth                        | }
> auth                        | query: ROLLBACK
> auth                        | /var/www/node_modules/typeorm/error/QueryFailedError.js:11
> auth                        |         var _this = _super.call(this) || this;

Do the newly generated secrey keys `AUTH_JWT_SECRET`, `JWT_SECRET`, `LEGACY_JWT_SECRET `and `ENCRYPTION_SERVER_KEY `have to match anything in the legacy server?

**Comment by mobitar** [comment]
Maybe try clearing the contents of the `migrations` table then try again? All secrets from the old server do need to match new server.

**Comment by joekerna** [comment]
My old .env file from the legacy server only had `SECRET_KEY_BASE=change123` (I accidently never changed that). That one does not appear in the new .env?!

Did the other ones not exist in the legacy server?

**Comment by ey-tsifry** [comment]
> How do I get the server to update the schema to the new one?

This is exactly the purpose of the database `migrations`, as specified in `DB_MIGRATIONS_PATH`.  (See https://orkhan.gitbook.io/typeorm/docs/migrations for background).  A migration is a diff that is run to make an incremental update to the database schema.

Based on the sample error message that you posted, it looks like the application was executing the expected migration workflow, but it was trying and failing to run the third migration in `DB_MIGRATIONS_PATH`: https://github.com/standardnotes/auth/blob/main/migrations/1610025371088-add_foreign_key_to_revoked_sessions.ts

Without seeing the other error messages, it's hard to know whether that means that it tried to run the first two migrations but the third failed, or if all of the migrations failed.  But either way it's probably worth trying to just clear out your `migrations` table per @mobitar's suggestion.  There may be references to migrations in there that conflict with or don't actually exist in  https://github.com/standardnotes/auth/blob/main/migrations.

> Do the newly generated secrey keys `AUTH_JWT_SECRET`, `JWT_SECRET`, `LEGACY_JWT_SECRET` and `ENCRYPTION_SERVER_KEY` have to match anything in the legacy server?
> My old .env file from the legacy server only had `SECRET_KEY_BASE=change123` (I accidently never changed that). That one does not appear in the new .env?!
> Did the other ones not exist in the legacy server?

It looks like these variables did exist in the last version of the legacy server:
https://github.com/standardnotes/syncing-server/blob/master/.env.sample
https://github.com/standardnotes/syncing-server/blob/master/docker/auth.env.sample
https://github.com/standardnotes/syncing-server/blob/master/docker/syncing-server-js.env.sample

However, these variables look more related to API authentication and data encryption than to DB authentication.  It's likely more important and relevant to make sure that the `DB_*` values in `.env` are correct.
