### ISSUE TITLE
Unable to register in a fresh server install

### ISSUE THREAD

**Issue by zkvvoob** [standardnotes/standalone#32]
**Describe the issue**
I've just finished setting up a fresh standalone syncing server using the docker-compose instructions. `./server.sh status` returns Up for all 6 services. Opening `http://localhost:3000/healthcheck` returns `OK`, too. Yet, when I try to register using either the desktop app (MacOS) or app.standardnotes.org, I get a message `Unknown error`.

**Service Versions (please complete the following information):**
 - syncing-server-js: 1.36.0
 - auth: 1.12.0
 - api-gateway: 1.20.0

**Logs**
**_standardnotes_syncing-server-js-worker_1_** 
`10.0.0.11 (10.0.0.11:3306) open,
10.0.0.11:3306 is up - executing command,
cache (172.26.0.2:6379) open,
cache:6379 is up - executing command,
syncing-server-js:3000 is unavailable yet - waiting for it to start,
syncing-server-js (172.26.0.3:3000) open,
syncing-server-js:3000 is up - executing command,
Starting Worker...,
yarn run v1.22.5,
$ node dist/bin/worker.js,
New Relic for Node.js was unable to bootstrap itself due to an error:,
Error: New Relic requires that you name this application!,
Set app_name in your newrelic.js file or set environment variable,
NEW_RELIC_APP_NAME. Not starting!,
    at createAgent (/var/www/node_modules/newrelic/index.js:145:11),
    at initialize (/var/www/node_modules/newrelic/index.js:84:15),
    at Object.<anonymous> (/var/www/node_modules/newrelic/index.js:37:3),
    at Module._compile (node:internal/modules/cjs/loader:1092:14),
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10),
    at Module.load (node:internal/modules/cjs/loader:972:32),
    at Function.Module._load (node:internal/modules/cjs/loader:813:14),
    at Module.require (node:internal/modules/cjs/loader:996:19),
    at require (node:internal/modules/cjs/helpers:92:18),
    at Object.<anonymous> (/var/www/dist/bin/worker.js:4:1),
{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"8d9474f46af5","pid":32,"time":"2021-07-25T07:46:38.123Z","msg":"Unable to find configuration file. If a configuration file is desired (common for non-containerized environments), a base configuration file can be copied from /var/www/node_modules/newrelic/newrelic.js and renamed to \"newrelic.js\" in the directory from which you will start your application. Attempting to start agent using environment variables."},
{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"8d9474f46af5","pid":32,"time":"2021-07-25T07:46:38.502Z","msg":"Unable to find configuration file. If a configuration file is desired (common for non-containerized environments), a base configuration file can be copied from /var/www/node_modules/@standardnotes/domain-events/node_modules/newrelic/newrelic.js and renamed to \"newrelic.js\" in the directory from which you will start your application. Attempting to start agent using environment variables."},
{"message":"Starting worker...","level":"info"},
{"message":"Alive and kicking!","level":"info"}`

**Comment by JaspalSuri** [comment]
Hi @zkvvoob,

Do any of the following  threads provide some insight that would help resolve the issue you're currently facing?

Server running but not accessible · standardnotes/standalone · Issue
https://github.com/standardnotes/standalone/issues/25

[BUG] Authentication fails with "Unknown error." · standardnotes/standalone  · Issue https://github.com/standardnotes/standalone/issues/21

QueryFailedError: Unknown column 'user.kp_created' in 'field list' · standardnotes/standalone  · Issue https://github.com/standardnotes/standalone/issues/23

“Unknown error” with version 1.34 · standardnotes/standalone  · Issue
https://github.com/standardnotes/standalone/issues/10

Credentials not working after migration from legacy selfhosted server · standardnotes/standalone · Issue https://github.com/standardnotes/standalone/issues/12

**Comment by e-zk** [comment]
I had the same issue on a fresh install.
Turns out uMatrix was blocking XHR requests to my domain from app.standardnotes.com.

Try disabling any adblock or privacy plugins you have temporarily to see if that fixes it.
