### ISSUE TITLE
api-gateway error 

### ISSUE THREAD

**Issue by MichiFr** [standardnotes/standalone#36]
**Describe the issue**
The api-gateway container is throwing this error `{"message":"Could not pass the request to http://auth:3000/auth/params on underlying service: undefined","level":"error"}` when signing in using an existing user after upgrading to the new standalone container.

**Service Versions (please complete the following information):**
 - syncing-server-js: latest
 - auth: latest
 - api-gateway: latest

**Logs**
`{"message":"Could not pass the request to http://auth:3000/auth/params on underlying service: undefined","level":"error"}`

I've upgrade from previous sync server to the new one, using docker-compose. All config files are adopted, the MySQL database is using the previous tables and data and obviously was migrated successfully after starting all containers, using command line `docker-compose -p "standardnotes2" up -d`.

I've checked all protocols of every single container and could not see any issues but the one mentioned above.
When signing in, using the web app of standardnotes, I just get and `Unknown error.`, that's all. At the same time the above error is logged. The sync server healthcheck is answering with `OK`. Hence, basically all should be well.

Any ideas what's wrong with that?

**Comment by eric-pierce** [comment]
I ran into a similar issue - are you using the "standalone" script to manage and configure the containers or are you manually setting up each container?

If it is the latter there are many additional configuration parameters that need to be set, and you can't use the "latest" tag, you have to use the versions of containers known to be compatible. See the versions listed for each container in https://github.com/standardnotes/standalone/blob/main/docker-compose.yml to determine the versions you should be using.

It looks like your migration may not have worked if the settings table is empty, I'm not sure when/how it is populated but I confirmed that it is configured for me. I migrated just my notes from the old setup to the new one (meaning no history, settings, etc) - I just exported the notes in plain text from the webui, set up the new server fresh, set up an account, and imported the notes file from the webui.

**Comment by MichiFr** [comment]
Thanks Eric! You hints pointed me into the right direction to get this task solved.

I started over with a fresh installation, after I managed to export all of my notes, using the desktop app (old version, which was still capable of accessing the old database).

Which steps did I take?
I've set up docker-compose.yml to **not** use latest container images but those that were suggested on Github's [original ](https://github.com/standardnotes/standalone/blob/main/docker-compose.yml) yaml file. Thanks Eric fort this valuable tip!

I then created a **new** database (inside my MySQL container) and gave the database user **all** privileges on that new database. Afterwards I started `docker-compose with command docker-compose -p "standardnotes2" up -d` from within the folder where all .env and the yml file are stored.

After a while I could register a new account and re-imported all previously exported (and encrypted) notes.

As far as I can see, the extensions still work like before (at least did not set up a new container) but the web app was updated to the latest version available.

Both, the desktop app as well as the web app work as expected so far.

**Comment by eric-pierce** [comment]
No problem @MichiFr glad it's working! I do want to call out that the approach you (and I) are taking isn't the intended method of self-hosting standardnotes - the SN team has built a script which maintains versioning, environment parameters, db, redis, and more in this repo to streamline the applications. Instructions for that can be found here: https://docs.standardnotes.org/self-hosting/docker/

Using the approach described on that page will be the easiest and least likely to break approach. I have different needs from infrastructure deployment and maintenance standpoint which doesn't lend itself to the "standalone" method which is why I've used another approach, but it is and will be much more work to maintain than the "standalone" method that SN team has put together.

**Comment by MichiFr** [comment]
Yes, you are correct of course! 

However, I'm running docker and standard notes containers on a Synology NAS and cannot perform all steps or use all of those scripts on my device that the SN team suggests me to use. 

I've read those instructions and I agree that the provided scripts are the way to go, but I feared that I will fail anytime soon because the instructions where not specific for any Synology NAS. 

So credits go for Rusty and his [blog](https://www.blackvoid.club/standard-notes-docker-self-hosted-alternative/). 
However, nevertheless I struggled very soon because of trying to migrate an existing setup instead of starting over with a fresh install. 

Anyway, I will have a look into those shell script(s) and see if they will ease at least an update of all containers in future.

**Comment by BobWs** [comment]
> Yes, you are correct of course!
> 
> However, I'm running docker and standard notes containers on a Synology NAS and cannot perform all steps or use all of those scripts on my device that the SN team suggests me to use.
> 
> I've read those instructions and I agree that the provided scripts are the way to go, but I feared that I will fail anytime soon because the instructions where not specific for any Synology NAS.
> 
> So credits go for Rusty and his [blog](https://www.blackvoid.club/standard-notes-docker-self-hosted-alternative/).
> However, nevertheless I struggled very soon because of trying to migrate an existing setup instead of starting over with a fresh install.
> 
> Anyway, I will have a look into those shell script(s) and see if they will ease at least an update of all containers in future.

I'm also running SN on a Synology NAS also with the help of Rusty and his great blog!, using the latest:tag
After the migration everything has been running and working fine for a view months until today when I tried to update to the containers.

These are my steps:
(Updated via docker-compose)

```
docker pull standardnotes/syncing-server-js:latest
docker pull standardnotes/api-gateway:latest
docker pull standardnotes/auth:latest
docker pull redis:latest
docker pull mariadb:latest

cd /volume1/docker/standardnotes/standalone
docker-compose -p "standardnotes" up -d
```

My output in terminal
```
redis is up-to-date
mariadb is up-to-date
Creating standardnotes-syncing-server ... done
Creating standardnotes-worker         ... done
Creating standardnotes-auth           ... done
Creating standardnotes-api-gateway    ... done
Creating standardnotes-auth-worker    ... done
```
But after the containers started I keep getting these errors in the standardnotes-auth container

```

Log viewer settings
Auto-refresh logs
Wrap lines
Display timestamps
Fetch
Search
Lines
Actions

yarn run v1.22.5

$ node dist/bin/server.js

{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"9b47a0bfe6ca","pid":31,"time":"2021-08-08T10:44:05.083Z","msg":"NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables."}

{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"9b47a0bfe6ca","pid":31,"time":"2021-08-08T10:44:09.387Z","msg":"NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables."}

INFO: All classes found using provided glob pattern "dist/migrations/*.js" : "dist/migrations/1606470249553-init_database.js,dist/migrations/1610015065194-add_revoked_sessions.js,dist/migrations/1610025371088-add_foreign_key_to_revoked_sessions.js,dist/migrations/1612191669523-add_roles_and_permissions.js,dist/migrations/1612255683992-add_roles_and_permissions_data.js,dist/migrations/1612433739754-add_more_roles_and_permissions.js,dist/migrations/1614678016791-add_user_settings.js,dist/migrations/1614771815912-add_encrypted_version.js,dist/migrations/1614775877590-add_encrypted_version_for_user.js,dist/migrations/1624434102642-update_roles_and_permissions.js,dist/migrations/1625164984414-change_setting_timestamps.js,dist/migrations/1625227894975-change_setting_value_size.js,dist/migrations/1625767770284-change_setting_value_to_nullable.js,dist/migrations/1625807999951-add_unique_setting_index.js,dist/migrations/1626268390207-remove_unique_setting_index.js,dist/migrations/1626689139110-add_user_subscriptions.js,dist/migrations/1626717016896-fix_subscription_foreign_key.js,dist/migrations/1627638504691-move_mfa_items_to_user_settings.js"

query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'standardnotes' AND `TABLE_NAME` = 'migrations'

query: SELECT * FROM `migrations` `migrations`  ORDER BY `id` DESC

No migrations are pending

/var/www/dist/src/Bootstrap/Env.js:22

            throw new Error(`Environment variable ${key} not set`);

Error: Environment variable WEBSOCKETS_API_URL not set

    at Env.get (/var/www/dist/src/Bootstrap/Env.js:22:19)
    at ContainerConfigLoader.load (/var/www/dist/src/Bootstrap/Container.js:200:80)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

db (172.19.0.5:3306) open
db:3306 is up - executing command
cache (172.19.0.4:6379) open
cache:6379 is up - executing command
syncing-server-js (172.19.0.2:3000) open
syncing-server-js:3000 is up - executing command
Starting Web...
```

So I reverted back to my previous version and everything is working fine.

Any ideas why I'm getting these errors after update? 
How to solve this?

**Comment by MichiFr** [comment]
Exactly the same errors on my side unless sbdy. gave the tip that I've to use the vary same image versions as in the provided docker composer file [here](https://github.com/standardnotes/standalone/blob/main/docker-compose.yml).

Which means: NOT using the latest versions but those specific as the above linked file tells us. Rusty's blog may be correct for the time of writing, but at the moment do not use latest for downloading images.

**Comment by BobWs** [comment]
> Exactly the same errors on my side unless sbdy. gave the tip that I've to use the vary same image versions as in the provided docker composer file [here](https://github.com/standardnotes/standalone/blob/main/docker-compose.yml).
> 
> Which means: NOT using the latest versions but those specific as the above linked file tells us. Rusty's blog may be correct for the time of writing, but at the moment do not use latest for downloading images.

Thanks for the tip!
I modified my docker-compose file with the versions as indicated in the example and everything works again without error message.

A bit of a strange way of updating though. It would be much more efficient if one could use the `latest:tag`, because now you have to change the versions every time for an update.
