### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by mustafamizrak** [standardnotes/standalone#4]
When, I execute 

```
./server.sh start
./server.sh logs 
```

I am getting the following logs

```
syncing-server-js_1         | [nodemon] starting `npx ts-node bin/server.ts`
syncing-server-js_1         | npm WARN exec The following package was not found and will be installed: ts-node
syncing-server-js-worker_1  | syncing-server-js:3000 is unavailable yet - waiting for it to start
auth_1                      | syncing-server-js:3000 is unavailable yet - waiting for it to start
auth-worker_1               | auth:3000 is unavailable yet - waiting for it to start
api-gateway_1               | auth:3000 is unavailable yet - waiting for it to start
syncing-server-js_1         | 
syncing-server-js_1         | /home/syncingserver/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:513
syncing-server-js_1         |     return new TSError(diagnosticText, diagnosticCodes)
syncing-server-js_1         |            ^
syncing-server-js_1         | TSError: ⨯ Unable to compile TypeScript:
syncing-server-js_1         | error TS5083: Cannot read file '/var/www/node_modules/@standardnotes/config/src/tsconfig.json'.
syncing-server-js_1         | 
syncing-server-js_1         |     at createTSError (/home/syncingserver/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:513:12)
syncing-server-js_1         |     at reportTSError (/home/syncingserver/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:517:19)
syncing-server-js_1         |     at create (/home/syncingserver/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:528:36)
syncing-server-js_1         |     at Object.register (/home/syncingserver/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:410:19)
syncing-server-js_1         |     at main (/home/syncingserver/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/bin.ts:151:19)
syncing-server-js_1         |     at Object.<anonymous> (/home/syncingserver/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/bin.ts:288:3)
syncing-server-js_1         |     at Module._compile (node:internal/modules/cjs/loader:1092:14)
syncing-server-js_1         |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
syncing-server-js_1         |     at Module.load (node:internal/modules/cjs/loader:972:32)
syncing-server-js_1         |     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
syncing-server-js_1         | npm notice 
syncing-server-js_1         | npm notice New minor version of npm available! 7.6.0 -> 7.14.0
syncing-server-js_1         | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.14.0>
syncing-server-js_1         | npm notice Run `npm install -g npm@7.14.0` to update!
syncing-server-js_1         | npm notice 
syncing-server-js_1         | [nodemon] app crashed - waiting for file changes before starting...
auth_1                      | syncing-server-js:3000 is unavailable yet - waiting for it to start
syncing-server-js-worker_1  | syncing-server-js:3000 is unavailable yet - waiting for it to start
auth-worker_1               | auth:3000 is unavailable yet - waiting for it to start
api-gateway_1               | auth:3000 is unavailable yet - waiting for it to start
syncing-server-js-worker_1  | syncing-server-js:3000 is unavailable yet - waiting for it to start
auth-worker_1               | auth:3000 is unavailable yet - waiting for it to start
auth_1                      | syncing-server-js:3000 is unavailable yet - waiting for it to start
api-gateway_1               | auth:3000 is unavailable yet - waiting for it to start
```

It seems there is a problem in configuration.
PS: I checkout main branch.

**Comment by karolsojko** [comment]
@mustafamizrak - can you try updating your server with `./server.sh update` and try again?

**Comment by mustafamizrak** [comment]
> @mustafamizrak - can you try updating your server with `./server.sh update` and try again?

Same. Nothing changed.

**Comment by mobitar** [comment]
Can you try:

```shell
yarn install
yarn run build
./server.sh start
```

If that still doesn't work, can you tell me if this file exists: `/var/www/node_modules/@standardnotes/config/src/tsconfig.json`

**Comment by mustafamizrak** [comment]
@mobitar It worked. I don't know why but it should be in container not in host.

**Comment by karolsojko** [comment]
@mustafamizrak are you using the `standalone` repo or the `syncing-server-js` repo for self-hosting?

`standalone` does not mount any volumes so `yarn install` and `yarn build` on local environment should not help in any way.

**Comment by mustafamizrak** [comment]
@karolsojko I am using `syncing-server-js`.

**Comment by karolsojko** [comment]
@mustafamizrak `syncing-server-js` is meant for development purposes only.

If you'd wish to self-host please use this repository and our official docs: https://docs.standardnotes.org/self-hosting/getting-started/

Let me know if that helps with your issue

**Comment by karolsojko** [comment]
closing this one as it's not related to this repository. Feel free to re-open if needed
