### ISSUE TITLE
Syncingserver-js won’t connect to database anymore

### ISSUE THREAD

**Issue by BobWs** [standardnotes/standalone#45]
**Describe the issue**

Syncing-server-js suddenly can’t connect to de database anymore.
Yesterday everything was working fine until this morning I’m having problems with Syncing-server.
See below what my logs shows.

Anyone know how to fix this without lossing all my data? 

**Service Versions (please complete the following information):**
 - syncing-server-js: 1.39.0
 - auth: 1.18.0
 - api-gateway: 1.24.0

**Logs**
If applicable, add logs to help debug your problem.
```
      
$ node dist/bin/server.js

{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"e40f01ce8559","pid":30,"time":"2021-09-12T06:00:27.649Z","msg":"NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables."}

{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"e40f01ce8559","pid":30,"time":"2021-09-12T06:00:29.858Z","msg":"NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables."}

INFO: All classes found using provided glob pattern "dist/migrations/*.js" : "dist/migrations/1606470249552-init_database.js,dist/migrations/1617615657558-add_extension_settings.js,dist/migrations/1629964808297-drop_unused_indexes.js,dist/migrations/1630318893601-refactor_calculating_integrity_hash.js,dist/migrations/1630417724617-restrict_content_type.js"

query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'standardnotes' AND `TABLE_NAME` = 'migrations'

query: SELECT * FROM `migrations` `migrations`  ORDER BY `id` DESC

query failed: SELECT * FROM `migrations` `migrations`  ORDER BY `id` DESC

error: Error: Table 'standardnotes.migrations' doesn't exist in engine

    at Packet.asError (/var/www/node_modules/mysql2/lib/packets/packet.js:712:17)

    at Query.execute (/var/www/node_modules/mysql2/lib/commands/command.js:28:26)

    at PoolConnection.handlePacket (/var/www/node_modules/mysql2/lib/connection.js:425:32)

    at PacketParser.onPacket (/var/www/node_modules/mysql2/lib/connection.js:75:12)

    at PacketParser.executeStart (/var/www/node_modules/mysql2/lib/packet_parser.js:75:16)

    at Socket.<anonymous> (/var/www/node_modules/mysql2/lib/connection.js:82:25)

    at Socket.emit (node:events:378:20)

    at Socket.EventEmitter.emit (node:domain:470:12)

    at addChunk (node:internal/streams/readable:313:12)

    at readableAddChunk (node:internal/streams/readable:288:9) {

  code: undefined,

  errno: 1932,

  sqlState: '42S02',

  sqlMessage: "Table 'standardnotes.migrations' doesn't exist in engine"

}

/var/www/node_modules/typeorm/error/QueryFailedError.js:11

        var _this = _super.call(this) || this;

                           ^


QueryFailedError: Table 'standardnotes.migrations' doesn't exist in engine

    at new QueryFailedError (/var/www/node_modules/typeorm/error/QueryFailedError.js:11:28)

    at Query.onResult (/var/www/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:216:45)

    at Query.execute (/var/www/node_modules/mysql2/lib/commands/command.js:30:14)

    at PoolConnection.handlePacket (/var/www/node_modules/mysql2/lib/connection.js:425:32)

    at PacketParser.onPacket (/var/www/node_modules/mysql2/lib/connection.js:75:12)

    at PacketParser.executeStart (/var/www/node_modules/mysql2/lib/packet_parser.js:75:16)

    at Socket.<anonymous> (/var/www/node_modules/mysql2/lib/connection.js:82:25)

    at Socket.emit (node:events:378:20)

    at Socket.EventEmitter.emit (node:domain:470:12)

    at addChunk (node:internal/streams/readable:313:12) {

  code: undefined,

  errno: 1932,

  sqlState: '42S02',

  sqlMessage: "Table 'standardnotes.migrations' doesn't exist in engine",

  query: 'SELECT * FROM `migrations` `migrations`  ORDER BY `id` DESC',

  parameters: []

}

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

db (172.19.0.3:3306) open

db:3306 is up - executing command

cache (172.19.0.2:6379) open

cache:6379 is up - executing command

Starting Web...

yarn run v1.22.5

$ node dist/bin/server.js

{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"e40f01ce8559","pid":31,"time":"2021-09-12T06:01:36.408Z","msg":"NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables."}

{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"e40f01ce8559","pid":31,"time":"2021-09-12T06:01:38.645Z","msg":"NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables."}

INFO: All classes found using provided glob pattern "dist/migrations/*.js" : "dist/migrations/1606470249552-init_database.js,dist/migrations/1617615657558-add_extension_settings.js,dist/migrations/1629964808297-drop_unused_indexes.js,dist/migrations/1630318893601-refactor_calculating_integrity_hash.js,dist/migrations/1630417724617-restrict_content_type.js"

query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'standardnotes' AND `TABLE_NAME` = 'migrations'

query: SELECT * FROM `migrations` `migrations`  ORDER BY `id` DESC

query failed: SELECT * FROM `migrations` `migrations`  ORDER BY `id` DESC

error: Error: Table 'standardnotes.migrations' doesn't exist in engine

    at Packet.asError (/var/www/node_modules/mysql2/lib/packets/packet.js:712:17)

    at Query.execute (/var/www/node_modules/mysql2/lib/commands/command.js:28:26)

    at PoolConnection.handlePacket (/var/www/node_modules/mysql2/lib/connection.js:425:32)

    at PacketParser.onPacket (/var/www/node_modules/mysql2/lib/connection.js:75:12)

    at PacketParser.executeStart (/var/www/node_modules/mysql2/lib/packet_parser.js:75:16)

    at Socket.<anonymous> (/var/www/node_modules/mysql2/lib/connection.js:82:25)

    at Socket.emit (node:events:378:20)

    at Socket.EventEmitter.emit (node:domain:470:12)

    at addChunk (node:internal/streams/readable:313:12)

    at readableAddChunk (node:internal/streams/readable:288:9) {

  code: undefined,

  errno: 1932,

  sqlState: '42S02',

  sqlMessage: "Table 'standardnotes.migrations' doesn't exist in engine"

}

/var/www/node_modules/typeorm/error/QueryFailedError.js:11

        var _this = _super.call(this) || this;

                           ^


QueryFailedError: Table 'standardnotes.migrations' doesn't exist in engine

    at new QueryFailedError (/var/www/node_modules/typeorm/error/QueryFailedError.js:11:28)

    at Query.onResult (/var/www/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:216:45)

    at Query.execute (/var/www/node_modules/mysql2/lib/commands/command.js:30:14)

    at PoolConnection.handlePacket (/var/www/node_modules/mysql2/lib/connection.js:425:32)

    at PacketParser.onPacket (/var/www/node_modules/mysql2/lib/connection.js:75:12)

    at PacketParser.executeStart (/var/www/node_modules/mysql2/lib/packet_parser.js:75:16)

    at Socket.<anonymous> (/var/www/node_modules/mysql2/lib/connection.js:82:25)

    at Socket.emit (node:events:378:20)

    at Socket.EventEmitter.emit (node:domain:470:12)

    at addChunk (node:internal/streams/readable:313:12) {

  code: undefined,

  errno: 1932,

  sqlState: '42S02',

  sqlMessage: "Table 'standardnotes.migrations' doesn't exist in engine",

  query: 'SELECT * FROM `migrations` `migrations`  ORDER BY `id` DESC',

  parameters: []

}

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by BobWs** [comment]
Solved it by deleting everything and start over. Imported the backups of all my users. 
Everything is working again.
Is the only way I could think off solving this issue.

**Comment by JaspalSuri** [comment]
Sorry to hear that. Thank you for letting us know what worked for you.
