### ISSUE TITLE
[BUG] syncing-server-js-standalone throws continual errors when attempting to import old database

### ISSUE THREAD

**Issue by mpatton125** [standardnotes/standalone#51]
**Service Versions (please complete the following information):**
```
             Container                          Repository                 Tag         Image Id      Size
-----------------------------------------------------------------------------------------------------------
api-gateway-standalone                standardnotes/api-gateway         1.25.1       b29b29a5a88c   602 MB
auth-standalone                       standardnotes/auth                1.22.1       3ae071814b36   811 MB
auth-worker-standalone                standardnotes/auth                1.22.1       3ae071814b36   811 MB
cache-standalone                      redis                             6.0-alpine   6960a2858b36   29.9 MB
db-standalone                         mysql                             5.6          8d06d2d16232   289 MB
syncing-server-js-standalone          standardnotes/syncing-server-js   1.42.1       7543b99652cd   920 MB
syncing-server-js-worker-standalone   standardnotes/syncing-server-js   1.42.1       7543b99652cd   920 MB
```

**Describe the bug**
syncing-server-js-standalone throws continual errors when attempting to import old database.

Error:

```
db ([2404:e80:43a9:2::27]:3306) open
db:3306 is up - executing command
cache ([2404:e80:43a9:2::22]:6379) open
cache:6379 is up - executing command
Starting Web...
yarn run v1.22.5
$ node dist/bin/server.js
{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"a279d23c3363","pid":30,"time":"2021-10-12T22:28:58.371Z","msg":"NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables."}
{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"a279d23c3363","pid":30,"time":"2021-10-12T22:28:58.706Z","msg":"NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables."}
/var/www/node_modules/typeorm/error/QueryFailedError.js:11
        var _this = _super.call(this) || this;
                           ^

QueryFailedError: Can't DROP 'index_revisions_on_item_uuid'; check that column/key exists
    at new QueryFailedError (/var/www/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.onResult (/var/www/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:216:45)
    at Query.execute (/var/www/node_modules/mysql2/lib/commands/command.js:30:14)
    at PoolConnection.handlePacket (/var/www/node_modules/mysql2/lib/connection.js:425:32)
    at PacketParser.onPacket (/var/www/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/var/www/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/var/www/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (node:events:378:20)
    at Socket.EventEmitter.emit (node:domain:470:12)
    at addChunk (node:internal/streams/readable:313:12) {
  code: 'ER_CANT_DROP_FIELD_OR_KEY',
  errno: 1091,
  sqlState: '42000',
  sqlMessage: "Can't DROP 'index_revisions_on_item_uuid'; check that column/key exists",
  query: 'DROP INDEX `index_revisions_on_item_uuid` ON `revisions`',
  parameters: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**
1. Dump old DB
2. Place old DB dump in data/import
3. Bring up new Docker stack
4. See error in logs

**Expected behavior**
Old DB dump to be imported into new stack and stack to complete starting.

**Logs**
Above.

The only reference to "index_revisions_on_item_uuid" I can find in my old DB dump is:

```
DROP TABLE IF EXISTS `revisions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `revisions` (
  `uuid` varchar(36) NOT NULL,
  `item_uuid` varchar(255) DEFAULT NULL,
  `content` mediumtext DEFAULT NULL,
  `content_type` varchar(255) DEFAULT NULL,
  `items_key_id` varchar(255) DEFAULT NULL,
  `enc_item_key` text DEFAULT NULL,
  `auth_hash` varchar(255) DEFAULT NULL,
  `creation_date` date DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`uuid`),
  KEY `index_revisions_on_created_at` (`created_at`),
  KEY `index_revisions_on_creation_date` (`creation_date`),
  KEY `index_revisions_on_item_uuid` (`item_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
```

**Comment by w0rp** [comment]
I get the same error when I try to start a fresh server with no data.

**Comment by mpatton125** [comment]
Hey there @karolsojko 

Thanks for the work, however I still get the following on fresh startup:

```
syncing-server-js-standalone | db:3306 is unavailable yet - waiting for it to start
syncing-server-js-standalone | db:3306 is unavailable yet - waiting for it to start
syncing-server-js-standalone | db:3306 is unavailable yet - waiting for it to start
syncing-server-js-standalone | db ([2404:e80:43a9:2::28]:3306) open
syncing-server-js-standalone | db:3306 is up - executing command
syncing-server-js-standalone | cache ([2404:e80:43a9:2::27]:6379) open
syncing-server-js-standalone | cache:6379 is up - executing command
syncing-server-js-standalone | Starting Web...
syncing-server-js-standalone | yarn run v1.22.5
syncing-server-js-standalone | $ node dist/bin/server.js
syncing-server-js-standalone | {"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"abc60aab90bb","pid":36,"time":"2021-10-30T03:40:38.763Z","msg":"NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables."}
syncing-server-js-standalone | {"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"abc60aab90bb","pid":36,"time":"2021-10-30T03:40:39.140Z","msg":"NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables."}
syncing-server-js-standalone | /var/www/node_modules/typeorm/error/QueryFailedError.js:11
syncing-server-js-standalone |         var _this = _super.call(this) || this;
syncing-server-js-standalone |                            ^
syncing-server-js-standalone |
syncing-server-js-standalone | QueryFailedError: Cannot add foreign key constraint
syncing-server-js-standalone |     at new QueryFailedError (/var/www/node_modules/typeorm/error/QueryFailedError.js:11:28)
syncing-server-js-standalone |     at Query.onResult (/var/www/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:216:45)
syncing-server-js-standalone |     at Query.execute (/var/www/node_modules/mysql2/lib/commands/command.js:30:14)
syncing-server-js-standalone |     at PoolConnection.handlePacket (/var/www/node_modules/mysql2/lib/connection.js:425:32)
syncing-server-js-standalone |     at PacketParser.onPacket (/var/www/node_modules/mysql2/lib/connection.js:75:12)
syncing-server-js-standalone |     at PacketParser.executeStart (/var/www/node_modules/mysql2/lib/packet_parser.js:75:16)
syncing-server-js-standalone |     at Socket.<anonymous> (/var/www/node_modules/mysql2/lib/connection.js:82:25)
syncing-server-js-standalone |     at Socket.emit (node:events:378:20)
syncing-server-js-standalone |     at Socket.EventEmitter.emit (node:domain:470:12)
syncing-server-js-standalone |     at addChunk (node:internal/streams/readable:313:12) {
syncing-server-js-standalone |   code: 'ER_CANNOT_ADD_FOREIGN',
syncing-server-js-standalone |   errno: 1215,
syncing-server-js-standalone |   sqlState: 'HY000',
syncing-server-js-standalone |   sqlMessage: 'Cannot add foreign key constraint',
syncing-server-js-standalone |   query: 'ALTER TABLE `revisions` ADD CONSTRAINT `FK_ab3b92e54701fe3010022a31d90` FOREIGN KEY (`item_uuid`) REFERENCES `items`(`uuid`) ON DELETE CASCADE ON UPDATE NO ACTION',
syncing-server-js-standalone |   parameters: []
syncing-server-js-standalone | }
syncing-server-js-standalone | error Command failed with exit code 1.
syncing-server-js-standalone | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by karolsojko** [comment]
@mpatton125 thanks for the feedback - updated the syncing-server-js version to `1.42.7` in the standalone - can you check if it works now?

**Comment by mpatton125** [comment]
@karolsojko Hey there!

Getting further. :)  Now it's failing similarly in "auth":

```
/var/www/node_modules/typeorm/error/QueryFailedError.js:11
        var _this = _super.call(this) || this;
                           ^
auth-standalone             |
QueryFailedError: Cannot add foreign key constraint
    at new QueryFailedError (/var/www/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.onResult (/var/www/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:216:45)
    at Query.execute (/var/www/node_modules/mysql2/lib/commands/command.js:30:14)
    at PoolConnection.handlePacket (/var/www/node_modules/mysql2/lib/connection.js:425:32)
    at PacketParser.onPacket (/var/www/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/var/www/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/var/www/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (node:events:378:20)
    at Socket.EventEmitter.emit (node:domain:470:12)
    at addChunk (node:internal/streams/readable:313:12) {
  code: 'ER_CANNOT_ADD_FOREIGN',
  errno: 1215,
  sqlState: 'HY000',
  sqlMessage: 'Cannot add foreign key constraint',
  query: 'ALTER TABLE `revoked_sessions` ADD CONSTRAINT `FK_b357d1397b82bcda5e6cc9b0062` FOREIGN KEY (`user_uuid`) REFERENCES `users`(`uuid`) ON DELETE CASCADE ON UPDATE NO ACTION',
  parameters: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I even tried the latest tagged version of "auth" and problem persists.  I took a look at the migrations files, but I couldn't see where there was a similar mismatch.  As far as I can see, revoked_sessions.user_uuid is the same length as users.uuid - both are 36.

I did note that sessions.user_uuid is created as 255 - but that shouldn't be causing this issue?

**Comment by karolsojko** [comment]
@mpatton125 can you see in your database dump that you are importing if there are any `revoked_sessions` present? This issue might be caused by the fact that foreign key is being created on data that is for example missing between `users` and `revoked_sessions`

**Comment by mpatton125** [comment]
@karolsojko There aren't any references to "revoked_sessions" at all in my dump or the legacy db, table name or otherwise.

**Comment by mpatton125** [comment]
I can give you a copy of my dbdump, if it will help progress?

**Comment by mpatton125** [comment]
I worked around this by downloading a backup from my old notes server and importing it to the new one.

**Comment by karolsojko** [comment]
@mpatton125 should we mark this one as closed in that case?

**Comment by mpatton125** [comment]
Yeah I guess we can.  I have the feeling that my import problem likely came from my source DB being so far behind current schema versions that it became problematic.

Thanks for all your help!
