### ISSUE TITLE
Registration not working (api-gateway error)

### ISSUE THREAD

**Issue by irmantask** [standardnotes/standalone#8]
Using ae8d483ab3f1391a7a255a6646cc9c01456db45f

Receiving error:
`TypeError: Cannot read property 'body' of undefined
    at HttpService.<anonymous> (/var/www/dist/src/Service/HttpService.js:89:67)
    at Generator.throw (<anonymous>)
    at rejected (/var/www/dist/src/Service/HttpService.js:18:65)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)`

**Comment by irmantask** [comment]
Hey, still can't register.

Using 84bdf9af0c09bda43730f1d2af8e3f13ca490aca

Error:
`RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
    at new NodeError (node:internal/errors:329:5)
    at ServerResponse.writeHead (node:_http_server:279:11)
    at ServerResponse._implicitHeader (node:_http_server:270:8)
    at write_ (node:_http_outgoing:746:9)
    at ServerResponse.end (node:_http_outgoing:835:5)
    at ServerResponse.send (/var/www/node_modules/inversify-express-utils/node_modules/express/lib/response.js:221:10)
    at HttpService.<anonymous> (/var/www/dist/src/Service/HttpService.js:87:47)
    at Generator.throw (<anonymous>)
    at rejected (/var/www/dist/src/Service/HttpService.js:18:65)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)`

**Comment by karolsojko** [comment]
@irmantask how are you registering? 

can you send me the request payload you are trying to use to register?

If you can attach more logs in a separate file that would be helpful

**Comment by irmantask** [comment]
@karolsojko i tried to create new account using macOS & Linux apps (same error everytime).

Request content in HAR (from Linux app):
https://pastebin.com/jVhzV6cN

**Comment by karolsojko** [comment]
@irmantask did you update your `standalone` setup with `./server.sh update` ? 

Can you please send the startup logs + and service versions you are running ?
